name: "Setup Go"
description: "Install Go using go.mod version and enable caching"
inputs:
  go-version-file:
    description: "Path to file with Go version"
    required: false
    default: go.mod
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache: true
    - name: Go version
      shell: bash
      run: go version
